/patrol_node:   # 必须与你启动时用的节点名一致
  ros__parameters:
    initial_point: [0.0, 0.0, 0.0]  # x,y,yaw

    target_points: [
      2.5, -2.0, 0.0,
      0.0, 3.0, 1.57,
      -3.5, 2.0, 0.0,
      0.0, -2.0, 1.57,
      0.0, 0.0, 0.0,
    ]
    
    use_sim_time: false

    img_save_path: "/home/isaac/pabot_ws/pabot_images"